trigger:
- development

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR'
        repository: 'chatmod'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(tag)'

    - task: CopyFiles@2
      displayName: Copy build manifests
      inputs:
        Contents: 'Build/onprem.yml' 
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish build manifests
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/Build/onprem.yml'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      
    - task: CopyFiles@2
      displayName: Copy build manifests
      inputs:
        Contents: 'Build/onprem.yml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish build manifests
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/Build/onprem.yml'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    